version: '3.8'

services:
  # 1. Database - PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      # Default DB (Baaki hum init script se banayenge)
      POSTGRES_DB: marketplace_main
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Auto-create databases for microservices
      - ./tools/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - marketplace-network

  # 2. Caching - Redis
  redis:
    image: redis:alpine
    container_name: marketplace-redis
    ports:
      - '6379:6379'
    networks:
      - marketplace-network

  # 3. Messaging - Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: marketplace-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - marketplace-network

  # 4. Messaging - Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: marketplace-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - marketplace-network

  # 5. Tooling - Kafka UI (For Debugging)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: marketplace-kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - marketplace-network

  # 6. NoSQL Database - MongoDB
  mongo:
    image: mongo:7.0
    container_name: marketplace-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
    networks:
      - marketplace-network

  # 7. Tooling - Mongo Express (Web UI for Mongo)
  mongo-express:
    image: mongo-express
    container_name: marketplace-mongo-express
    restart: always
    ports:
      - '8081:8081'  # 8080 Kafka UI ke paas hai, isliye 8081 use kiya
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
    networks:
      - marketplace-network

volumes:
  postgres_data:
  mongo_data:

networks:
  marketplace-network:
    driver: bridge